name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Setup Node
        uses: actions/setup-node@v4

      - name: Install dependencies
        run: bun install
      - name: Build UI Core
        run: bun run build --filter=@melv1c/ui-core

      - name: Check code formatting
        run: bun run check
